# Generated by Django 4.0.1 on 2022-01-12 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tarjeta', models.BigIntegerField(null=True)),
                ('nombre_tarjeta', models.CharField(max_length=40)),
                ('cvv', models.IntegerField()),
                ('fecha_vencimiento', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Transaccion_Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=25)),
                ('usuario_comprador', models.CharField(max_length=25)),
                ('fecha_peticion', models.DateField(null=True)),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.pago')),
            ],
            options={
                'verbose_name': 'Transaccion_Pendiente',
                'verbose_name_plural': 'Transacciones_Pendientes',
            },
        ),
        migrations.CreateModel(
            name='Transaccion_Autorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=25)),
                ('usuario_comprador', models.CharField(max_length=25)),
                ('fecha_peticion', models.DateField(null=True)),
                ('fecha_autorizado', models.DateField(null=True)),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.pago')),
                ('usuario_authorizador', models.ForeignKey(max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaccion_Pendiente',
                'verbose_name_plural': 'Transacciones_Pendientes',
            },
        ),
    ]
