# Generated by Django 4.0.1 on 2022-01-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Abierto'), (2, 'Cerrado'), (3, 'Manual')], default=1)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
