# Generated by Django 4.0.1 on 2022-01-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_estado_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_servidor',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
